### ISSUE TITLE
接收用户在界面上传的图片，数据库出错

### ISSUE THREAD

**Issue by xuanxuan178** [birds-oucteam9/birds-team9-web#23]
使用Django自带的服务器，想要连接MySQL，进入超级管理员界面。
Django连接MySQL数据库出错：
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "D:\software\Python3.7\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "D:\software\Python3.7\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "D:\software\Python3.7\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\software\Python3.7\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "D:\software\Python3.7\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "D:\software\Python3.7\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\software\Python3.7\lib\site-packages\django\contrib\auth\models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "D:\software\Python3.7\lib\site-packages\django\contrib\auth\base_user.py", line 48, in <module>
    class AbstractBaseUser(models.Model):
  File "D:\software\Python3.7\lib\site-packages\django\db\models\base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "D:\software\Python3.7\lib\site-packages\django\db\models\base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "D:\software\Python3.7\lib\site-packages\django\db\models\options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "D:\software\Python3.7\lib\site-packages\django\db\__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "D:\software\Python3.7\lib\site-packages\django\db\utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "D:\software\Python3.7\lib\site-packages\django\db\utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "D:\software\Python3.7\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\software\Python3.7\lib\site-packages\django\db\backends\mysql\base.py", line 36, in <module>
    raise ImproperlyConfigured('mysqlclient 1.4.0 or newer is required; you have %s.' % Database.__version__)
django.core.exceptions.ImproperlyConfigured: mysqlclient 1.4.0 or newer is required; you have 0.10.1.

目前正在寻找解决办法。

**Comment by xuanxuan178** [comment]
这两天在准备六级考试，没有去解决这个问题。

**Comment by xuanxuan178** [comment]
已解决，但不知其所以然。
参考博客如下：[django报错解决mysqlclient 1.4.0 or newer is required； you have 0.10.0.](https://blog.csdn.net/weixin_42289273/article/details/108609194)
